

[modelscope]
base_url='https://api-inference.modelscope.cn/v1'
api_key='ms-45ca1833-a198-4f34-9710-bbdb87c99d16'
default_model='Deepseek-ai/deepseek-v4-pro'
models=[
    'Deepseek-ai/deepseek-v4-pro',
    'Qwen/Qwen3.5-397B-A17B',
    'ZhipuAI/GLM-5.1'
]

